"""workout table

Revision ID: 4a37b7c6c8be
Revises: 8871ce91a5f3
Create Date: 2019-01-24 06:49:33.156793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a37b7c6c8be'
down_revision = '8871ce91a5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_timestamp'), 'workout', ['timestamp'], unique=False)
    op.create_index(op.f('ix_workout_title'), 'workout', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_title'), table_name='workout')
    op.drop_index(op.f('ix_workout_timestamp'), table_name='workout')
    op.drop_table('workout')
    # ### end Alembic commands ###
