"""empty message

Revision ID: 760d80da90c3
Revises: f78156f3089b
Create Date: 2019-02-08 10:34:24.196170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760d80da90c3'
down_revision = 'f78156f3089b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set', sa.Column('progression', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_set_progression'), 'set', ['progression'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_progression'), table_name='set')
    op.drop_column('set', 'progression')
    # ### end Alembic commands ###
