"""empty message

Revision ID: 813b1a707676
Revises: 760d80da90c3
Create Date: 2019-02-10 14:53:13.353647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813b1a707676'
down_revision = '760d80da90c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'workout_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('workout_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'exercises', 'workout', ['workout_id'], ['id'])
    # ### end Alembic commands ###
